### ISSUE TITLE
Video Stuck on iPhone 7 and  7 Plus occassionally

### ISSUE THREAD

**Issue by alfredthekkan** [andreipitis/ASPVideoPlayer#10]
I use ASPVideoPlayer as a splash video. I don't show any controls. On iPhone 7  and 7 plus, the video is sometimes stuck. Even if i restart the app or reinstall the app from Xcode the issue persists. If I restart the phone the video starts playing again. I tried a fix here https://github.com/alfredthekkan/ASPVideoPlayer

I added an observer to frame rate. But sometimes the player.rate is 1. Still the video is stuck. 
Any help on this is appreciated.

**Comment by andreipitis** [comment]
Hi @alfredthekkan. 

Unfortunately I don't have a physical iPhone 7 to test this out. Can you reproduce the issue on any other device (iPhone 5S, 6, 6S) or on the simulator? If so, could you describe your setup, or maybe create a small test project to illustrate the bug and provide me with the link?
