### ISSUE TITLE
A lot ASPVideoPlayerView don't play video

### ISSUE THREAD

**Issue by NorbertSzydlowski** [andreipitis/ASPVideoPlayer#13]
Hi,

I have got UIPager with one ASPVideoPlayerView at it.

I am scrolling and for some time player don't start. State is readyToPlay and closure is triger but movie don't start.

Any idea how to fix this?

**Comment by andreipitis** [comment]
Hi @NorbertSzydlowski,

Are you trying to play a local or a remote video? If it's a remote video the delay might be caused by a weak network connection. The player starts but it doesn't have enough data to start playing reliably.
The only thing to do would be to modify the view and implement a callback to let you know when the video is buffering and when it's ready.

**Comment by NorbertSzydlowski** [comment]
It is local video. Ready is trigger but dont Play.25.07.2017 1:36 PM Andrei-Sergiu Pițiș <notifications@github.com> napisał(a):Hi @NorbertSzydlowski,
Are you trying to play a local or a remote video? If it's a remote video the delay might be caused by a weak network connection. The player starts but it doesn't have enough data to start playing reliably.
The only thing to do would be to modify the view and implement a callback to let you know when the video is buffering and when it's ready.

**Comment by andreipitis** [comment]
Does the video play normally when you don't use a pager?
Does the same thing happen with other videos?

It would be great if you could create a simple sample app where you reproduce the issue and provide me with a link. It's had to debug this kind of issue without the actual code.

**Comment by NorbertSzydlowski** [comment]
Yes, video Play normaly until i scroll more than 20 items. (Videos).More scroll, stop playing all videos.You can reproduce with pager and a lot of viewplayer pages25.07.2017 1:51 PM Andrei-Sergiu Pițiș <notifications@github.com> napisał(a):Does the video play normally when you don't use a pager?
Does the same thing happen with other videos?
It would be great if you could create a simple sample app where you reproduce the issue and provide me with a link. It's had to debug this kind of issue without the actual code.

**Comment by andreipitis** [comment]
If you are using a standard `UIPageViewController` make sure your page `ViewControllers` get deinitialized properly.
As far as I know, iOS has a limit as to how many players can exist simultaneously, so if your `ViewControllers` don't get deinitialized, it's not going to work after a certain point, in your case after the 20th page. 

 If you are using a custom implementation, the same rule applies, make sure you don't leak memory.
