### ISSUE TITLE
KVO and time observation breaks on iOS 11

### ISSUE THREAD

**Issue by iwasrobbed** [andreipitis/ASPVideoPlayer#16]
I filed an issue with Apple about this, but it seems like all the observations break on iOS 11 (periodic time observer and KVO). Even the new Swift 4 KVO methods are broken.

It works fine on iOS 10 devices/simulators but doesn't work at all on iOS 11 or 11.1 (even against older binaries built against iOS 10 using Xcode 8.3.3).

Other players like [Player](https://github.com/piemonte/Player) do not have this problem so it strikes me as either a race condition or a framework bug.

I'll update this once I hear back, but just wanted to make you aware.

**Comment by andreipitis** [comment]
Hi @iwasrobbed , I tried running the sample project both on simulators and on devices (iOS 11, 11.0.1, 11.0.2) and it always worked fine.

**Comment by iwasrobbed** [comment]
(Sorry for the delayed response) Thanks for looking! Seems like it was just a local issue
