### ISSUE TITLE
how can i stop video?

### ISSUE THREAD

**Issue by choiks14** [andreipitis/ASPVideoPlayer#20]
how can i stop video?

plz help me.

**Comment by andreipitis** [comment]
Hi @choiks14,

Your question is a bit vague, but I'm assuming you wish to stop the video playback programatically.

If you are using `ASPVideoPlayerView`, you can stop the video playback using the `stopVideo()` method:
```Swift
let videoPlayer = ASPVideoPlayerView()
...
videoPlayer.stopVideo()
```

If you are using `ASPVideoPlayer`, you can use the `stop()` method of the `videoPlayerControls` property:
```Swift
let videoPlayer = ASPVideoPlayer()
...
videoPlayer.videoPlayerControls.stop()
```
