### ISSUE TITLE
How to play specific video

### ISSUE THREAD

**Issue by ErAshu** [andreipitis/ASPVideoPlayer#21]
Hi Andre,
I am using `ASPVideoPlayer` and passing 4 url for video.
Here is my code
`videoPlayer.videoAssets = assetURL`
        `videoPlayer.gravity = .aspectFit`
        `videoPlayer.shouldLoop = true`
        `videoPlayer.startPlayingWhenReady = true`
Its Playing from 1st url.
Is there any variable to pass which video have to play.

For example, I have to play 3rd video, i clicked on 3rd item of collection view then 3rd video should play. This time its playing from 1st.

Please help me asap. I have to upload this project ASAP. Only this function is left.

Thanks in advance.

**Comment by andreipitis** [comment]
Hi @ErAshu ,

`ASPVideoPlayer` doesn't have a builtin functionality that would suit your needs for this particular case, however you could still achieve your desired result.

You could keep track of the video index that you wish to play, and just shuffle around the urls in the array before passing them to the player.
```
[url1, url2, url3, url4] => [url3, url4, url1, url2]
```

Assuming that you are using the default controls, you could also force the player to jump a few items by using:
```Swift
videoPlayer.videoPlayerControls.didPressNextButton?()
```

**Comment by ErAshu** [comment]
Hi @andreipitis 
I have done this with 
`videoPlayer.videoPlayerControls.didPressNextButton?()`
Get the index and call this method in GCD.
