### ISSUE TITLE
How to change video speed

### ISSUE THREAD

**Issue by waseem-shah-ios** [andreipitis/ASPVideoPlayer#22]
Want to change video speed like 1x, 2x etc

**Comment by andreipitis** [comment]
Hi @waseem-shah-ios , right now there is no way to change the speed, but it seems like a good feature. I'll try to add it in the next version.

**Comment by waseem-shah-ios** [comment]
I achieve this in your library by using user default. I know this is not a good way , but I did this because of time shortage.

**Comment by RyadPasha** [comment]
> 

How??!

**Comment by RyadPasha** [comment]
But how @waseem-shah-ios?!!

**Comment by waseem-shah-ios** [comment]
open var preferredRate: Float = 1.0

you can by use this variable
