### ISSUE TITLE
How I show placeholder image in player and when player load video then remove it? 

### ISSUE THREAD

**Issue by waseem-shah-ios** [andreipitis/ASPVideoPlayer#23]
I want to show image as place holder and when video load then play video.

**Comment by andreipitis** [comment]
Hi @waseem-shah-ios , you can do this with ```ASPVideoPlayerView```, using the event callback ```readyToPlayVideo```. The closure will be called when the video is loaded and ready to play. 

Unfortunately you can't do this using ```ASPVideoPlayer``` since it uses ```ASPVideoPlayerView``` in it's implementation and does not forward the events.

**Comment by waseem-shah-ios** [comment]
@andreipitis 
I achieve this by using local notification centre. I add image view and fired notification in your library when video is ready to play and remove image view from parent view.
