### ISSUE TITLE
How to detect stopping video

### ISSUE THREAD

**Issue by bluekey630** [andreipitis/ASPVideoPlayer#29]
I am using ASPVideoPlayer
I need to detect stopping video, so I need to go to other screen at that time

**Comment by andreipitis** [comment]
Hi @bluekey630 ,

`ASPVideoPlayer` does not currently support this functionality, only `ASPVideoPlayerView` does.
I will try to add the callback functionality to `ASPVideoPlayer` soon.

**Comment by andreipitis** [comment]
Version [4.1.0](https://github.com/andreipitis/ASPVideoPlayer/releases/tag/4.1.0) adds a delegate property to `ASPVideoPlayer` to handle events.
