### ISSUE TITLE
Value of type 'ASPVideoPlayer' has no member 'startedVideo'

### ISSUE THREAD

**Issue by ForGuru** [andreipitis/ASPVideoPlayer#33]
I have just upgraded my project and I found this issue.

What shall I do? Cant afford too much modification

**Comment by andreipitis** [comment]
Hi @ForGuru, judging by the error message it seems that you were using an older version of the framework. If you still wish to use the same functionality, simply replace `ASPVideoPlayer` with `ASPVideoPlayerView` within your code. That should fix all the errors with minimal changes.
