### ISSUE TITLE
Controls Visible

### ISSUE THREAD

**Issue by sarmadmakhdoom** [andreipitis/ASPVideoPlayer#34]
Hi it would be great help if you add controls Visible/Invisible method in the newly added delegate too so if we want to do certain stuff when controls are on the screen, we can do that. If you would like me to fork and send a pull request for this, let me know.

**Comment by andreipitis** [comment]
Hi @sarmadmakhdoom , this is a good suggestion. The functionality is now available in [4.2.0](https://github.com/andreipitis/ASPVideoPlayer/releases/tag/4.2.0).

**Comment by sarmadmakhdoom** [comment]
Thanks, good work. Really appreciated
