### ISSUE TITLE
rtsp/rtmp support?

### ISSUE THREAD

**Issue by fukemy** [andreipitis/ASPVideoPlayer#35]
hello. that's great lib. Does it support for rtsp/rtmp?

**Comment by andreipitis** [comment]
Hi @fukemy ,

`ASPVideoPlayer` is based on `AVPlayer` so it is limited by what the underlying `AVPlayer` can do. As far as I know `AVPlayer` only supports HTTP Live Streaming.

**Comment by fukemy** [comment]
ok thanks you. i found ffmpeg is still best choice for it at this moment
