### ISSUE TITLE
Cannot pause when pause button is clicked for audio

### ISSUE THREAD

**Issue by kwakueshun** [andreipitis/ASPVideoPlayer#36]
This library is meant for  video but I digged through the code base and realized that it used AVPlayer so I tried to use to play and mp3 and it works fine but play and pause functionality does not work when it is an audio file. Is there any reason why this does not work?

**Comment by andreipitis** [comment]
Hi @kwakueshun, I just tried playing an mp3 file with the example app and I did not encounter any issue. Could you give me some more details about your setup or a sample project?

**Comment by kwakueshun** [comment]
Turns out it was a problem from my backend API. This is resolved now.
