### ISSUE TITLE
Property 'self.newVideo' not initialized at super.init call

### ISSUE THREAD

**Issue by BrianBananalab** [andreipitis/ASPVideoPlayer#43]

**Comment by andreipitis** [comment]
Hi @BrianyinIOS , could you provide some more details about this issue?
What version of XCode are you using?
Is this occurring when using the framework through CocoaPods or if you try to build the source?

**Comment by BrianBananalab** [comment]
The Xcode version I use is 10.2.1. This problem has been solved, because the cached ASPlayer in my cocopods is not the latest one, I just need to clear it and reinstall it. Finally, thank you for your reply！
