### ISSUE TITLE
can not seek video when put in sliding panel

### ISSUE THREAD

**Issue by fukemy** [andreipitis/ASPVideoPlayer#44]
Hello. First thanks you for very nice project. I just starting with it
When put ASPVideoVC inside ContainerView, ContainerView inside SlidingPanel, the problem is I can not slide the progress. Can you help? 

As the screenshot below, i cant seek the progress only max 1 cm, after that it stop highlight then back to normal size
![Screen Shot 2019-06-19 at 17 25 19](https://user-images.githubusercontent.com/8202437/59758044-3ce7b780-92b7-11e9-9972-a4d8a6526154.png)

When debug i saw the func cancelTracking always call when i seek the progressbar

**Comment by andreipitis** [comment]
Hi @fukemy , 

I'm guessing your SlidingPanel has a `GestureRecognizer` attached that intercepts the touch events which leads to `cancelTracking` being called.

There are a couple of ways that I can think of to solve the issue:
 1. Set the `cancelsTouchesInView` of the `GestureRecognizer` to false to allow the touch event to be forwarded to the progress bar.

 2. Use the `UIGestureRecognizerDelegate` methods to prevent the `GestureRecognizer` from firing if the touch location is inside of the video player:
 ```Swift
    func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        let point = gestureRecognizer.location(in: gestureRecognizer.view)
        //You might need to do a conversion here depending on the position of your video player. However if it's at the very top this should work.
        return videoPlayer.frame.contains(point) == false
    }
```

**Comment by fukemy** [comment]
it work. Thanks
