### ISSUE TITLE
'CMTime' has no member 'kCMTimeZero'

### ISSUE THREAD

**Issue by naveedmcs** [andreipitis/ASPVideoPlayer#46]
ASPVideoPlayer-master/ASPVideoPlayer/Classes/ASPVideoPlayerView.swift:391:52: Type 'CMTime' has no member 'kCMTimeZero'

**Comment by andreipitis** [comment]
Hi @nvdmcs,

It looks like you are using an older version of the framework. 
If you update to the latest version the error should go away.
