### ISSUE TITLE
Property 'self.readyToPlayVideo' not initialized at super.init call

### ISSUE THREAD

**Issue by mdfalcon104** [andreipitis/ASPVideoPlayer#50]
In swift 5 I got this issue while compiling. Shall we set a default value for readyToPlayVideo?

**Comment by andreipitis** [comment]
Hi @dlpigpen

I'm not getting this error and `readyToPlayVideo` already has a default value ( `open var readyToPlayVideo: VoidClosure = nil` ).

Are you using the latest version of the framework?
Which version of XCode are you using?

**Comment by bamz3r** [comment]
Same error, but in diferent place

Property 'self.newVideo' not initialized at super.init call

ASPVideoPlayer v. 5.0.2 
xcode 11.5
Mac OS 10.15.5

fixed after updating ASPVideoPlayer to the latest version
