### ISSUE TITLE
Resize Button Is Outside of View

### ISSUE THREAD

**Issue by stephendanielxxx** [andreipitis/ASPVideoPlayer#52]
Hi thank your for sharing this wonderful library, I tried your library to show video from URL and working great, the only problem is the Fullscreen button is always located outside of the view so I can't clicked it . So is possible to fix the Fullscreen button position? My view looked like this 

<img width="358" alt="Resize Button Outside" src="https://user-images.githubusercontent.com/70615773/93752627-230af200-fc29-11ea-8b62-997946465a2d.png">

**Comment by andreipitis** [comment]
Hi @stephendanielxxx ,

This is a bug, the button should not be visible in this case. I fixed this in the latest release, but you can also fix it by setting `videoPlayer.clipsToBounds = true`.
The resize button should only be visible if you set the `resizeClosure` on the video player.
[Here](https://github.com/andreipitis/ASPVideoPlayer/blob/4b78b96754a469e8bacb6fcb390c038034781257/Example/ASPVideoPlayer/PlayerViewController.swift#L48) is an example implementation of the resizing.

**Comment by stephendanielxxx** [comment]
Thank you very much for the information, I will try the solution 👍 :)
